### ISSUE TITLE
Remote upload to Adafruit Blue Fruit Sense failed zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Lukasz-Madry** [platformio/platform-nordicnrf52#166]
Hello, I am trying to test my adafruit board on platform io and I cannot remotely upload a built program onto the adafruit board. I have a windows 10 computer doing the remote upload and a remote agent set up on a linux laptop. The upload fails, returning the following error: 

`
Uploading .pio/build/adafruit_feather_nrf52840_sense/firmware.hex
Traceback (most recent call last):
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/adafruit-nrfutil.py", line 12, in <module>
    cli()
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/nordicsemi/__main__.py", line 290, in serial
    dfu = Dfu(package, dfu_transport=serial_backend)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/nordicsemi/dfu/dfu.py", line 66, in __init__
    self.manifest = Package.unpack_package(self.zip_file_path, self.unpacked_zip_path)
  File "/home/kasshev/.platformio/packages/tool-adafruit-nrfutil/site-packages/nordicsemi/dfu/package.py", line 361, in unpack_package
    with ZipFile(package_path, 'r') as pkg:
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
`

Uploading the same program locally is successful

**Comment by Lukasz-Madry** [comment]
Additionally, doing a reverse process (Windows acting as an agent, Linux uploading the code) returns the same set of errors. I have read that a similar issue has been resolved in the past, by installing the latest version of PlatformIO, but according to pio update I am running the newest version of the IDE [https://github.com/platformio/platformio-vscode-ide/issues/1598#issue-579772285](url)
